fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

entreprise:
    resource: "@EntrepriseBundle/Resources/config/routing.yml"
    prefix:   /entreprise

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
